dbt_demo:
  outputs:
    dev:
      account: jthgfgu/mg61909
      database: RAW
      password: dbtpassword123
      role: transform
      schema: AIRBNB
      threads: 1
      type: snowflake
      user: DEV7814
      warehouse: COMPUTE_WH
  target: dev
