dbt_demo:
  outputs:
    dev:
      type: snowflake
      account: jthgfgu-mg61909
      user: dbt
      password: dbtPassword123
      role: transform
      database: RAW
      warehouse: COMPUTE_WH
      schema: AIRBNB
      threads: 1
  target: dev
